import type {Metadata} from "next";

import {Open_Sans} from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vitalis - Centro de salud integral",
  description: "Generated by appncy",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <Header />
      <body className={`${openSans.className} bg-[#ededed]`}>{children}</body>
    </html>
  );
}
