import type {Metadata} from "next";

import {Open_Sans} from "next/font/google";
import {Suspense} from "react";

import "./globals.css";
import {AuthProvider} from "@/contexts/AuthContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vitalis - Centro de salud integral",
  description: "Generated by appncy",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className={`${openSans.className} bg-[#ededed]`}>
        <AuthProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <Header />
          </Suspense>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
