import type {Metadata} from "next";

import {Open_Sans} from "next/font/google";

import "@/app/globals.css";
import Footer from "@/components/Footer";
import {Clients} from "@/components/ui/Icons";

import Panel from "./components/Panel";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vitalis - Sistema de administración y gestión de clientes",
  description: "Generated by appncy",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className={`${openSans.className} bg-[#ededed]`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
